alchemic-version: v2.1
Timezone: Australia/Melbourne
author: Derek Clarkson

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
