//
//  ALCMacro.h
//  Alchemic
//
//  Created by Derek Clarkson on 23/07/2015.
//  Copyright © 2015 Derek Clarkson. All rights reserved.
//

@import Foundation;

/**
 Tags any class that is generated by a macro.
 */
@protocol ALCMacro <NSObject>

@end
