//
//  NSObject+Alchemic.h
//  alchemic
//
//  Created by Derek Clarkson on 15/08/2015.
//  Copyright © 2015 Derek Clarkson. All rights reserved.
//

@import Foundation;

// Must import or Generics don't resolve.
#import "ALCBuilderDependencyManager.h"
#import "ALCVariableDependency.h"

/**
 Extension to NSObject.
 */
@interface NSObject (Alchemic)

/**
 Executes the specified selector and returns the result.

 @param selector  The selector to execute.
 @param arguments The arguments required by the selector.

 @return The value generated by the method.
 */
-(id) invokeSelector:(SEL) selector arguments:(NSArray *) arguments;

/**
 Injects an object with dependencies.

 @param object The object to be injected.
 */
-(void) injectWithDependencies:(ALCBuilderDependencyManager<ALCVariableDependency *> *) dependencyManager;

@end
