//
//  NSObject+Alchemic.h
//  Alchemic
//
//  Created by Derek Clarkson on 7/02/2016.
//  Copyright © 2016 Derek Clarkson. All rights reserved.
//

@import Foundation;
@import ObjectiveC;

#import "ALCResolvable.h"

@protocol ALCDependency;
@protocol ALCModel;

@interface NSObject (Alchemic)

/**
 Executes the specified selector and returns the result.

 @param selector  The selector to execute.
 @param arguments The arguments required by the selector.

 @return The value generated by the method.
 */
-(id) invokeSelector:(SEL) selector arguments:(NSArray<id<ALCDependency>> *) arguments;

/**
 Executes the specified selector and returns the result.

 @param selector  The selector to execute.
 @param arguments The arguments required by the selector.

 @return The value generated by the method.
 */
+(id) invokeSelector:(SEL) selector arguments:(NSArray<id<ALCDependency>> *) arguments;

-(void) resolveFactoryWithResolvingStack:(NSMutableArray<NSString *> *) resolvingStack
                           resolvingFlag:(BOOL *) resolvingFlag
                                   block:(void (^) (void)) block;

-(void) resolveDependencyWithResolvingStack:(NSMutableArray<NSString *> *) resolvingStack
                                   withName:(NSString *) name
                                      model:(id<ALCModel>) model;

-(BOOL) dependenciesReady:(NSArray<id<ALCResolvable>> *) dependencies
            resolvingFlag:(BOOL *) resolvingFlag;

@end
